services:
  openrgpd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openrgpd_app
    volumes:
      - ./app:/var/www/html
      - ./config.sample.php:/var/www/config.php
      - ./config/php/php.ini:/usr/local/etc/php/php.ini  # Pour personnaliser la configuration PHP
    ports:
      - "30401:80"
    networks:
      - openrgpd-network
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: mariadb_db
    ports:
      - "30403:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: openrgpd
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf 
    networks:
      - openrgpd-network

networks:
  openrgpd-network:
    driver: bridge

volumes:
  db_data:
